my_string = input ("Ваша строка с произвольным текстом: ")
len_string = len(my_string)
print("Длинна введеной строки: ", len_string)
print ("Строка в верхнем регистре: ", my_string. upper())
print ("Строка в нижнем регистре: ", my_string. lower())
print("Строка без пробелов: ", my_string. replace(" ", ""))
print(my_string [0])
print(my_string [-1])